name    'rtyler-opengrok'
version '0.1.0'
source 'git://github.com/rtyler/puppet-opengrok.git'
author 'R. Tyler Croy <tyler@monkeypox.org>'
license 'Apache 2.0'
summary 'Module for managing the OpenGrok source cross referencing tool'
description 'Module for managing the OpenGrok source cross referencing tool'
project_page 'https://github.com/rtyler/puppet-opengrok'
